name = "MinFinVol"
uuid = "f0fdf6c0-f929-4610-836a-3570bc34851f"
authors = ["pedrosecchi67 <pedrosecchimail@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
